apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-backups
  labels:
    app: mongodb-backups
data:
  config.yaml: |
    name: integration
    retention: 1w
    schedule: '0 0 * * *'
    timeout: 15m
    tmpPath: /tmp
    mongodb:
      host: localhost
      port: 27017
    bucket:
      s3:
        name: bucket-name
        region: eu-west-1
